spring:
  cloud:
    gateway:
      routes:
        ## service1
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
